import type { SourceDefinition } from "../domain/types.js";

export const APPROVED_PUBLIC_SOURCES: readonly SourceDefinition[] = Object.freeze([
  {
    sourceId: "openai-news-rss",
    name: "OpenAI News RSS",
    publisher: "OpenAI",
    region: "GLOBAL",
    sourceKind: "rss",
    endpointUrl: "https://openai.com/news/rss.xml",
    homepageUrl: "https://openai.com/news/",
    pollIntervalMinutes: 120,
  },
  {
    sourceId: "google-ai-blog-rss",
    name: "Google AI Blog RSS",
    publisher: "Google",
    region: "GLOBAL",
    sourceKind: "rss",
    endpointUrl: "https://blog.google/technology/ai/rss/",
    homepageUrl: "https://blog.google/technology/ai/",
    pollIntervalMinutes: 120,
  },
  {
    sourceId: "qwen3-github-releases",
    name: "Qwen3 GitHub Releases",
    publisher: "QwenLM",
    region: "CN",
    sourceKind: "github_releases",
    endpointUrl: "https://api.github.com/repos/QwenLM/Qwen3/releases?per_page=10",
    homepageUrl: "https://github.com/QwenLM/Qwen3/releases",
    pollIntervalMinutes: 120,
  },
  {
    sourceId: "paddle-github-releases",
    name: "PaddlePaddle GitHub Releases",
    publisher: "PaddlePaddle",
    region: "CN",
    sourceKind: "github_releases",
    endpointUrl: "https://api.github.com/repos/PaddlePaddle/Paddle/releases?per_page=10",
    homepageUrl: "https://github.com/PaddlePaddle/Paddle/releases",
    pollIntervalMinutes: 180,
  },
  {
    sourceId: "ollama-github-releases",
    name: "Ollama GitHub Releases",
    publisher: "Ollama",
    region: "GLOBAL",
    sourceKind: "github_releases",
    endpointUrl: "https://api.github.com/repos/ollama/ollama/releases?per_page=10",
    homepageUrl: "https://github.com/ollama/ollama/releases",
    pollIntervalMinutes: 60,
  },
  {
    sourceId: "transformers-github-releases",
    name: "Transformers GitHub Releases",
    publisher: "Hugging Face",
    region: "GLOBAL",
    sourceKind: "github_releases",
    endpointUrl: "https://api.github.com/repos/huggingface/transformers/releases?per_page=10",
    homepageUrl: "https://github.com/huggingface/transformers/releases",
    pollIntervalMinutes: 120,
  },
]);
